FROM golang:1.16-alpine as builder
WORKDIR /app
RUN go get github.com/urfave/negroni

COPY server.go /app
RUN go build /server.go

FROM bitnami/minideb:stretch
RUN mkdir -p /app
WORKDIR /app
COPY --from=builder /go/server .
RUN useradd -r -u 1001 -g root nonroot
RUN chown -R nonroot /app
USER nonroot
ENV PORT=8080
CMD /app/server