apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeployment
  namespace: myns
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: gocontainer
        image: sherqodirov/go_demo_app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred        
