apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_deployment
  labels:
    app: go_application
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go_application
  template:
    metadata:
      labels:
        app: go_application
    spec:
      containers:
      - name: go_app_container
        image: sherqodirov/go_demo_app
        ports:
        - containerPort: 3000