apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go_application
        image: sherqodirov/go_demo_app
        ports:
        - containerPort: 80