apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  docker-server: xxxxxxxxxxxxx= #registry-1.docker.io/v2/
  docker-username: xxxxxxxxxxxxx= 
  docker-password: xxxxxxxxxxxxx==
  docker-email: xxxxxxxxxxxxx== 