apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  docker-server: xxxxx= #registry-1.docker.io/v2/
  docker-username: xxxxx= 
  docker-password: xxxxx=
  docker-email: xxxxx== 